#!/usr/bin/env python3
"""Convert a PNG into a C++ indexed-color sprite array for TamaBailey.

Each input pixel is matched to the closest entry in the 16-color sprite
palette defined in lib/tama_core/include/tama/colors.h. Fully transparent
input pixels map to palette index 0 (the transparent sentinel).

Usage:
  python scripts/png_to_sprite.py input.png \\
    --name bailey_idle_a \\
    --output lib/tama_core/src/sprites_user.cpp
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    sys.exit("This script needs Pillow.  Install with:  pip install Pillow")

# Mirror of kSpritePalette (RGB triplets in the same order as colors.h).
PALETTE = [
    (  0,   0,   0),  # 0 transparent sentinel (won't be matched)
    ( 60,  35,  10),  # 1 outline
    (140,  80,  35),  # 2 body
    (200, 140,  80),  # 3 highlight
    (  0,   0,   0),  # 4 black
    (255, 255, 255),  # 5 white
    (255, 150, 170),  # 6 pink
    (245, 220, 175),  # 7 cream
    (220,  40,  40),  # 8 red
    ( 90, 200,  90),  # 9 green
    ( 90, 150, 245),  # 10 blue
    (245, 215,  40),  # 11 yellow
    (245, 150,  30),  # 12 orange
    (140, 140, 140),  # 13 gray
    ( 70,  70,  70),  # 14 dark gray
    (210, 210, 210),  # 15 light gray
]


def closest_index(rgb: tuple[int, int, int]) -> int:
    best, best_d = 1, 10**9
    # Skip index 0; transparency is decided by alpha, not color.
    for i in range(1, len(PALETTE)):
        pr, pg, pb = PALETTE[i]
        d = (pr - rgb[0]) ** 2 + (pg - rgb[1]) ** 2 + (pb - rgb[2]) ** 2
        if d < best_d:
            best, best_d = i, d
    return best


def convert(image_path: Path, name: str) -> tuple[int, int, list[int]]:
    img = Image.open(image_path).convert("RGBA")
    w, h = img.size
    pixels = list(img.getdata())
    indices = []
    for r, g, b, a in pixels:
        if a < 128:
            indices.append(0)
        else:
            indices.append(closest_index((r, g, b)))
    return w, h, indices


def emit_cpp(name: str, w: int, h: int, indices: list[int]) -> str:
    lines = [
        "// Auto-generated by scripts/png_to_sprite.py -- do not edit by hand.",
        "#include <cstdint>",
        "",
        "namespace tama {",
        "",
        f"constexpr int {name}_W = {w};",
        f"constexpr int {name}_H = {h};",
        f"const uint8_t {name}[{w * h}] = {{",
    ]
    for y in range(h):
        row = ", ".join(f"{indices[y * w + x]:>2}" for x in range(w))
        lines.append(f"  {row},")
    lines += ["};", "", "}  // namespace tama", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("input", type=Path, help="PNG to convert")
    ap.add_argument("--name", required=True, help="C++ identifier for the array")
    ap.add_argument("--output", type=Path, default=None,
                    help="Output .cpp path (default: stdout)")
    args = ap.parse_args()

    w, h, indices = convert(args.input, args.name)
    src = emit_cpp(args.name, w, h, indices)
    if args.output is None:
        print(src)
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(src)
        print(f"Wrote {args.output} ({w}x{h}, {len(indices)} bytes of indices)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
